# Generated by Django 5.0.1 on 2024-01-14 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='new_quiz-73def4df-8d39-4a2a-b555-254ba7a5688c', max_length=225),
        ),
    ]
