# Generated by Django 5.0.1 on 2024-01-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quizzes_creator_alter_quizzes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz_app.question'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='new_quiz-b34ce4cf-bfd7-45db-be29-7b40401c28da', max_length=225),
        ),
    ]
