# Generated by Django 5.0.1 on 2024-01-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_answer_question_alter_quizzes_title'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz_app.quizzes'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.course'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='medium', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='new_quiz-92e6e8f0-639c-49e0-a7b7-a5b453d36d7d', max_length=225),
        ),
    ]
